### ISSUE TITLE
Plugin failing on Shutdown event

### ISSUE THREAD

**Issue by salvadornico** [tjjfvi/OctoPrint-IFTTT#9]
Hi, I had the plugin working correctly up until a couple of days ago. It was set up to fire on shutdown, and this is the log output after it stopped working:

```
019-01-08 12:26:48,978 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2019-01-08 12:26:48,993 - octoprint.plugin - ERROR - Error while calling plugin IFTTT
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 230, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_IFTTT/__init__.py", line 36, in on_event
    payload = payload_thunk()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_IFTTT/__init__.py", line 32, in <lambda>
    payload_thunk = lambda: { "value1": value_thunks[0](), "value2": value_thunks[1](), "value3": value_thunks[2]() }
IndexError: list index out of range
```

It seems similar to #1, but that was already marked as fixed and I'm on the latest version. Any idea what's wrong?

**Comment by tjjfvi** [comment]
@salvadornico: I think the bug might have been reintroduced in v1.1.0; could you install the `beta` branch to confirm the fix?

**Comment by tjjfvi** [comment]
Try installing via this URL:
    https://github.com/tjjfvi/OctoPrint-IFTTT/archive/beta.zip

**Comment by salvadornico** [comment]
@tjjfvi The beta branch did the trick 👌

**Comment by tjjfvi** [comment]
Merged!
